package org.csapi.wsdl.parlayx.payment.amount_charging.v2_1._interface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-03-19T15:42:30.991+07:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebService(targetNamespace = "http://www.csapi.org/wsdl/parlayx/payment/amount_charging/v2_1/interface", name = "AmountCharging")
@XmlSeeAlso({org.csapi.schema.parlayx.payment.amount_charging.v2_1.local.ObjectFactory.class, org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class, org.csapi.schema.parlayx.payment.v2_1.ObjectFactory.class})
public interface AmountCharging {

    @RequestWrapper(localName = "chargeAmount", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.amount_charging.v2_1.local.ChargeAmount")
    @WebMethod
    @ResponseWrapper(localName = "chargeAmountResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.amount_charging.v2_1.local.ChargeAmountResponse")
    public void chargeAmount(
        @WebParam(name = "endUserIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        java.lang.String endUserIdentifier,
        @WebParam(name = "charge", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        org.csapi.schema.parlayx.common.v2_1.ChargingInformation charge,
        @WebParam(name = "referenceCode", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        java.lang.String referenceCode
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;

    @RequestWrapper(localName = "refundAmount", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.amount_charging.v2_1.local.RefundAmount")
    @WebMethod
    @ResponseWrapper(localName = "refundAmountResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.amount_charging.v2_1.local.RefundAmountResponse")
    public void refundAmount(
        @WebParam(name = "endUserIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        java.lang.String endUserIdentifier,
        @WebParam(name = "charge", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        org.csapi.schema.parlayx.common.v2_1.ChargingInformation charge,
        @WebParam(name = "referenceCode", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/amount_charging/v2_1/local")
        java.lang.String referenceCode
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;
}
