package com.ericsson.raso.sef.auth.permissions;

import java.io.Serializable;

public enum AuthorizationPrinciple implements Serializable {
	ACCESS_ALL,
	ACCESS_READ_ONLY,
	ACCESS_CREATE_NEW,
	ACCESS_UPDATE,
	ACCESS_DELETE,
	
	DOMAIN_ALL,
	
	DOMAIN_SUBSCRIBER_ALL,
	DOMAIN_SUBSCRIBER_META,
	DOMAIN_SUBSCRIBER_WORKFLOW,
	DOMAIN_SUBSCRIBER_LIFE_CYCLE,
	DOMAIN_SUBSCRIBER_MVNO_ALL,
	DOMAIN_SUBSCRIBER_MVNO_OWN,
	DOMAIN_SUBSCRIBER_MARKET_ALL,
	DOMAIN_SUBSCRIBER_MARKET_OWN,
	
	
	DOMAIN_SUBSCRIPTION_ALL,
	DOMAIN_SUBSCRIPTION_META,
	DOMAIN_SUBSCRIPTION_LIFECYCLE,
	
	DOMAIN_PRODUCT_ALL,
	DOMAIN_PRODUCT_BUSINESS_ALL,
	DOMAIN_PRODUCT_BUSINESS_OWN,
	DOMAIN_PRODUCT_TECHNICAL_ALL,
	DOMAIN_PRODUCT_TECHNICAL_OWN,
	DOMAIN_PRODUCT_PRICE_ALL,
	DOMAIN_PRODUCT_PRICE_OWN,
	
	
	DOMAIN_SERVICE_ALL,
	DOMAIN_SERVICE_FULFILLMENT,
	DOMAIN_SERVICE_COST_ALL,
	DOMAIN_SERVICE_COST_OWN,
	DOMAIN_SERVICE_BUSINESS_ALL,
	DOMAIN_SERVICE_BUSINESS_OWN,
	DOMAIN_SERVICE_TECHNICAL_ALL,
	DOMAIN_SERVICE_TECHNICAL_OWN,
	
	
	DOMAIN_PARTNER_ALL,
	DOMAIN_PARTNER_META,
	DOMAIN_PARTNER_LIFECYCLE,
	DOMAIN_PARTNER_SUBSCRIPTIONS_SELF,
	DOMAIN_PARTNER_SUBSCRIPTIONS_ALL,
	DOMAIN_PARTNER_PRODUCTS_SELF,
	DOMAIN_PARTNER_PRODUCTS_ALL,
	DOMAIN_PARTNER_SETTLEMENT_SELF,
	DOMAIN_PARTNER_SETTLEMENT_ALL,
	
	DOMAIN_USER_ALL,
	DOMAIN_USER_USER,
	DOMAIN_USER_GROUP,
	DOMAIN_USER_PRIVILEGES,
	
	
	SERVICE_CTXT_ALL,
	SERVICE_CTXT_INTERFACE,
	SERVICE_CTXT_PRIMITIVE,
	SERVICE_CTXT_PARAMETER,
	;

	
}
