package com.ericsson.raso.sef.cg.engine;

import com.ericsson.raso.sef.core.StatusCode;

public enum ResponseCode implements StatusCode {
	
	DIAMETER_MULTI_ROUND_AUTH(1001,"DIAMETER_MULTI_ROUND_AUTH"),
	DIAMETER_SUCCESS(2001, "DIAMETER_SUCCESS"),
	DIAMETER_LIMITED_SUCCESS(2002, "DIAMETER_LIMITED_SUCCESS"),
	DIAMETER_COMMAND_UNSUPPORTED(3001,"DIAMETER_COMMAND_UNSUPPORTED"),
	DIAMETER_UNABLE_TO_DELIVER(3002,"DIAMETER_UNABLE_TO_DELIVER"),
	DIAMETER_REALM_NOT_SERVED(3003,"DIAMETER_REALM_NOT_SERVED"),
	DIAMETER_TO_BUSY(3004, "DIAMETER_TO_BUSY"),
	DIAMETER_LOOP_DETECTED(3005,"DIAMETER_LOOP_DETECTED"),
	DIAMETER_REDIRECT_INDICATION(3006,"DIAMETER_REDIRECT_INDICATION"),
	DIAMETER_APPLICATION_UNSUPPORTED(3007,"DIAMETER_APPLICATION_UNSUPPORTED"),
	DIAMETER_INVALID_HDR_BITS(3008,"DIAMETER_INVALID_HDR_BITS"),
	DIAMETER_INVALID_AVP_BITS(3009,"DIAMETER_INVALID_AVP_BITS"),
	DIAMETER_UNKNOWN_PEER(3010,"DIAMETER_UNKNOWN_PEER"),
	DIAMETER_AUTHENTICATION_REJECTED(4001,"DIAMETER_AUTHENTICATION_REJECTED"),
	DIAMETER_OUT_OF_SPACE(4002,"DIAMETER_OUT_OF_SPACE"),
	ELECTION_LOST(4003,"ELECTION_LOST"),
	DIAMETER_END_USER_SERVICE_DENIED(4010,"DIAMETER_END_USER_SERVICE_DENIED"),
	DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE(4011,"DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE"),
	DIAMETER_CREDIT_LIMIT_REACHED(4012,"DIAMETER_CREDIT_LIMIT_REACHED"),
	DIAMETER_AVP_UNSUPPORTED(5001,"DIAMETER_AVP_UNSUPPORTED"),
	DIAMETER_UNKNOWN_SESSION_ID(5002, "DIAMETER_UNKNOWN_SESSION_ID"),
	DIAMETER_AUTHORIZATION_REJECTED(5003,"DIAMETER_AUTHORIZATION_REJECTED"),
	DIAMETER_INVALID_AVP_VALUE(5004,"DIAMETER_INVALID_AVP_VALUE"),
	DIAMETER_MISSING_AV(5005,"DIAMETER_MISSING_AVP"),
	DIAMETER_RESOURCES_EXCEEDED(5006,"DIAMETER_RESOURCES_EXCEEDED"),
	DIAMETER_CONTRADICTING_AVPS(5007,"DIAMETER_CONTRADICTING_AVPS"),
	DIAMETER_AVP_NOT_ALLOWED(5008,"DIAMETER_AVP_NOT_ALLOWED"),
	DIAMETER_AVP_OCCURS_TOO_MANY_TIMES(5009,""),
	DIAMETER_NO_COMMON_APPLICATION(5010,"DIAMETER_NO_COMMON_APPLICATION"),
	DIAMETER_UNSUPPORTED_VERSION(5011,"DIAMETER_NO_COMMON_APPLICATION"),
	DIAMETER_UNABLE_TO_COMPLY(5012, "DIAMETER_UNABLE_TO_COMPLY"),
	DIAMETER_INVALID_BIT_IN_HEADER(5013,"DIAMETER_INVALID_BIT_IN_HEADER"),
	DIAMETER_INVALID_AVP_LENGTH(5014,"DIAMETER_INVALID_AVP_LENGTH"),
	DIAMETER_INVALID_MESSAGE_LENGTH(5015,"DIAMETER_INVALID_MESSAGE_LENGTH"),
	DIAMETER_INVALID_AVP_BIT_COMBO(5016,"DIAMETER_INVALID_AVP_BIT_COMBO"),
	DIAMETER_NO_COMMON_SECURITY(5017,"DIAMETER_NO_COMMON_SECURITY"),
	DIAMETER_USER_UNKNOWN(5030,"DIAMETER_USER_UNKNOWN"),
	DIAMETER_RATING_FAILED(5031,"DIAMETER_RATING_FAILED"),
	SUBSCRIBER_GRACE_NOT_ALLOWED(8001,"SUBSCRIBER_GRACE_NOT_ALLOWED"),
	SUBSCRIBER_INSUFFICIENT_BALANCE(8002,"SUBSCRIBER_INSUFFICIENT_BALANCE"),
	SUBSCRIBER_NOT_FOUND(8003,"SUBSCRIBER_NOT_FOUND"),
	SUBSCRIBER_PREACTIVE_NOT_ALLOWED(8004,"SUBSCRIBER_PREACTIVE_NOT_ALLOWED"),
	SUBSCRIBER_LOCKED(8005,"SUBSCRIBER_LOCKED"),
	SUBSCRIBER_RECYCLE_NOT_ALLOWED(8006,"SUBSCRIBER_RECYCLE_NOT_ALLOWED");
	private final int code;
	private final String message;
	
	private ResponseCode(final int code, final String message) {
		this.code = code;
		this.message = message;
	}

	@Override
	public int getCode() {
		return code;
	}

	@Override
	public String getMessage() {
		return message;
	}
}
