package com.ericsson.raso.sef.bes.engine.transaction;

import java.util.Date;

public enum Constants {
	
	/* 
	 * All constants needed for Transaction & Orchestration 
	 */
	CREATE_SUSBCRIBER,
	UPDATE_SUBSCRIBER,
	USECASES,
	USE_CASE_EVAL,
	ORCHESTRATION, 
	ORCHESTRATION_TASK_MAPPER,
	TRANSACTION_STATUS, 
	TRANSACTION_STEPS, 
	TRANSACTION_STEP_STATUS,
	
	/*
	 * All constants needed for functional logic execution
	 */
	SUBSCRIPTION_ID, 
	READ_SUBSCRIBER,
	READ_SUBSCRIBER_ACTIVATION_DATE,
	READ_SUBSCRIBER_SUPERVISION_EXPIRY_DATE,
	READ_SUBSCRIBER_SERVICE_FEE_EXPIRY_DATE,
	READ_SUBSCRIBER_SERVICE_OFFERING_ID,
	READ_SUBSCRIBER_SERVICE_OFFERING_ACTIVE_FLAG,
	READ_SUBSCRIBER_ACTIVATION_STATUS_FLAG,
	READ_SUBSCRIBER_NEGATIVE_BARRING_STATUS_FLAG,
	READ_SUBSCRIBER_SUPERVISION_PERIOD_WARNING_ACTIVE_FLAG,
	READ_SUBSCRIBER_SERVICE_FEE_PERIOD_WARNING_ACTIVE_FLAG,
	READ_SUBSCRIBER_SUPERVISION_PERIOD_EXPIRY_FLAG,
	READ_SUBSCRIBER_SERVICE_FEE_PERIOD_EXPIRY_FLAG,
	READ_SUBSCRIBER_TWO_STEP_ACTIVATION_FLAG,
	READ_SUBSCRIBER_OFFER_INFO_OFFER_ID,
	READ_SUBSCRIBER_OFFER_INFO_START_DATE,
	READ_SUBSCRIBER_OFFER_INFO_EXPIRY_DATE,
	READ_SUBSCRIBER_OFFER_INFO_START_DATE_TIME,
	READ_SUBSCRIBER_OFFER_INFO_EXPIRY_DATE_TIME,
	
	READ_BALANCES_DEDICATED_ACCOUNT_ID,
	READ_BALANCES_DEDICATED_ACCOUNT_VALUE_1,
	READ_BALANCES_DEDICATED_ACCOUNT_VALUE_2,
	READ_BALANCES_DEDICATED_ACCOUNT_EXPIRY_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_START_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_PAM_SERVICE_ID,
	READ_BALANCES_DEDICATED_ACCOUNT_OFFER_ID,
	READ_BALANCES_DEDICATED_ACCOUNT_PRODUCT_ID,
	READ_BALANCES_DEDICATED_ACCOUNT_REAL_MONEY_FLAG,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_EXPIRY_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_EXPIRY_VALUE_1,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_EXPIRY_VALUE_2,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_ACCESSIBLE_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_ACCESSIBLE_VALUE_1,
	READ_BALANCES_DEDICATED_ACCOUNT_CLOSEST_ACCESSIBLE_VALUE_2,
	READ_BALANCES_DEDICATED_ACCOUNT_SUB_DA_VALUE_1,
	READ_BALANCES_DEDICATED_ACCOUNT_SUB_DA_VALUE_2,
	READ_BALANCES_DEDICATED_ACCOUNT_SUB_DA_START_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_SUB_DA_EXPIRY_DATE,
	READ_BALANCES_DEDICATED_ACCOUNT_ACTIVE_VALUE_1,
	READ_BALANCES_DEDICATED_ACCOUNT_ACTIVE_VALUE_2,
	READ_BALANCES_DEDICATED_ACCOUNT_UNIT_TYPE,
	READ_BALANCES_DEDICATED_ACCOUNT_COMPOSITE_DA_FLAG,
	READ_BALANCES_OFFER_INFO_OFFER_ID,
	READ_BALANCES_OFFER_INFO_START_DATE,
	READ_BALANCES_OFFER_INFO_EXPIRY_DATE,
	READ_BALANCES_OFFER_INFO_START_DATE_TIME,
	READ_BALANCES_OFFER_INFO_EXPIRY_DATE_TIME,

	

}
