package com.ericsson.raso.sef.bes.engine.transaction;

import java.util.Date;

public enum Constants {
	
	/* 
	 * All constants needed for Transaction & Orchestration 
	 */
	CREATE_SUSBCRIBER, 
	USECASES,
	USE_CASE_EVAL,
	ORCHESTRATION, 
	ORCHESTRATION_TASK_MAPPER,
	TRANSACTION_STATUS, 
	TRANSACTION_STEPS, 
	TRANSACTION_STEP_STATUS,
	
	/*
	 * All constants needed for functional logic execution
	 */
	SUBSCRIPTION_ID, 
	READ_SUBSCRIBER,
	READ_SUBSCRIBER_ACTIVATION_DATE,
	READ_SUBSCRIBER_SUPERVISION_EXPIRY_DATE,
	READ_SUBSCRIBER_SERVICE_FEE_EXPIRY_DATE,
	READ_SUBSCRIBER_SERVICE_OFFERING_ID,
	READ_SUBSCRIBER_SERVICE_OFFERING_ACTIVE_FLAG,
	READ_SUBSCRIBER_ACTIVATION_STATUS_FLAG,
	READ_SUBSCRIBER_NEGATIVE_BARRING_STATUS_FLAG,
	READ_SUBSCRIBER_SUPERVISION_PERIOD_WARNING_ACTIVE_FLAG,
	READ_SUBSCRIBER_SERVICE_FEE_PERIOD_WARNING_ACTIVE_FLAG,
	READ_SUBSCRIBER_SUPERVISION_PERIOD_EXPIRY_FLAG,
	READ_SUBSCRIBER_SERVICE_FEE_PERIOD_EXPIRY_FLAG,
	READ_SUBSCRIBER_TWO_STEP_ACTIVATION_FLAG,
	READ_SUBSCRIBER_OFFER_INFO_OFFER_ID,
	READ_SUBSCRIBER_OFFER_INFO_START_DATE,
	READ_SUBSCRIBER_OFFER_INFO_EXPIRY_DATE,
	READ_SUBSCRIBER_OFFER_INFO_START_DATE_TIME,
	READ_SUBSCRIBER_OFFER_INFO_EXPIRY_DATE_TIME;
	
	

}
