
package org.csapi.wsdl.parlayx.common.v2_0.faults;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-03-19T15:42:32.161+07:00
 * Generated source version: 2.6.0.redhat-60024
 */

@WebFault(name = "PolicyException", targetNamespace = "http://www.csapi.org/schema/parlayx/common/v2_1")
public class PolicyException extends Exception {
    
    private org.csapi.schema.parlayx.common.v2_1.PolicyException policyException;

    public PolicyException() {
        super();
    }
    
    public PolicyException(String message) {
        super(message);
    }
    
    public PolicyException(String message, Throwable cause) {
        super(message, cause);
    }

    public PolicyException(String message, org.csapi.schema.parlayx.common.v2_1.PolicyException policyException) {
        super(message);
        this.policyException = policyException;
    }

    public PolicyException(String message, org.csapi.schema.parlayx.common.v2_1.PolicyException policyException, Throwable cause) {
        super(message, cause);
        this.policyException = policyException;
    }

    public org.csapi.schema.parlayx.common.v2_1.PolicyException getFaultInfo() {
        return this.policyException;
    }
}
