package vasclient.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-19T23:42:05.917+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:VASClient/wsdl", name = "VASClientSEI")
@XmlSeeAlso({vasclient.types.ObjectFactory.class})
public interface VASClientSEI {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendToSPS", targetNamespace = "urn:VASClient/types", className = "vasclient.types.SendToSPS")
    @WebMethod
    @ResponseWrapper(localName = "sendToSPSResponse", targetNamespace = "urn:VASClient/types", className = "vasclient.types.SendToSPSResponse")
    public java.lang.String sendToSPS(
        @WebParam(name = "String_1", targetNamespace = "")
        java.lang.String string1
    );
}
