package com.ericsson.raso.sef.smart.subscriber.response;

import com.ericsson.raso.sef.core.StatusCode;

public enum ErrorCode implements StatusCode {

	success(0, "Successs"),
	internalServerError(11614, "internalSystemError"),
	invalidParamValue(11610, "Invalid parameter value"),
	rechargeTypeIsNotDefined(4, "Recharge Type is not defined"),
	internalSystemError(13400, "internalSystemError"),
	subscriberLocked(601, "Subscriber locked or barred"),
	invalidAdministrationData(4030, "Invalid administration data"),
	insufficientCredit(301, "Insufficient Credit"),
	operationInvalid(4002, "Operation invalid"),
	invalidParameterValue(4012, "invalid parameter value"),
	maxCreditViolation(506, "Threshold violation"),
	invalidAccount(504, "Invalid account"),
	insufficientBalanceForOperation(4005, "insufficient balance for operation"),
	insufficientBalanceForPeriodicalActivity(4006, "insufficient balance for periodical activity"),
	invalidCustomerLifecycleStateRecycle(602, "Invalid customer lifecycle state"),
	invalidCustomerLifecycleState(402, "Invalid customer lifecycle state"),
	invalidOperationState(4020, "invalid operation state"),
	lexicalError(11200, "lexical Error"),
	invalidSubscriberStateForRequiredPackageUseCaseOperation(4021, "invalid subscriber state for required package use case operation"),
	unsupportedEventClass(500, "Unsupported Event Class"),
	systemError(13100, "cannot instantiate transaction"),
	creditBelowLimit(502, "Credit below limit"),
	unknownInternalErrorInSMAF(7500, "Unknown internal error in SMAF"),
	smafHTTPInterfaceIsNotReady(7501, "SMAF HTTP Interface is not ready"),
	authorizationRequiredForThisSMAFHTTPRequest(7502, "Authorization is required for this SMAF HTTP request"),
	requestedCATIsNotAvailable(7503, "A requested CAT is not available"),
	userCanNotBeLogged(7550, "The user {0} can not be logged in:	Unknown user"),
	passwordExpiredAndMustBeChanged(7551, "The password expired and must be changed"),
	userIsLocked(7552, "The user is locked. "),
	incorrectPassword(7553, "Incorrect password"),
	internalErrorDatabaseAccessException(7554, "Internal error: A database access exception occurred"),
	problemsWithTrafficLimitControl(7600, "Problems with Traffic Limit Control:configuratedCounterName  "),
	trafficLimitViolation(7601, "Traffic Limit Violation: traffic limit reached for counter "),
	unsupportedSMAFHTTPRequest(7650, "Unsupported SMAF HTTP request"),
	missingOperationLineTextCommand(7651, "Missing operation line in text command"),
	missingDataLineTextCommand(7652, "Missing data line in text command for operation "),
	unknownServiceName(7653, "Unknown service name"),
	partIDInvalid(7654, "The partID of the chunk is invalid, the request is ignored"),
	errorReceivingChunkedRequest(7655, "Error while receiving a chunked request"),
	errorServiceNotAccessedClusterType(7656, "The Distribution service Servicename may not be accessed on cluster type"),
	smafHTTPRequestNotSupported(7660, "SMAF HTTP request not supported or not allowed for transfer-encoding"),
	smafHTTPUnsupportedEncoding(7661, "SMAF HTTP unsupported encoding"),
	invalidSSLDistinguishedName(7662, "Invalid SSL distinguished name"),
	noSSLDistinguishedName(7663, "No SSL distinguished name"),
	userHasNoFunctionRightForSSLAuthentication(7664, "The user has no FunctionRight for SSL authentication "),
	userHasNoFunctionRightForNormalAuthentication(7665, "The user has no FunctionRight for Normal authentication "),
	userHasNoFunctionRightsWorkInterfaceSMAF(7666, "The user has no FunctionRights to work with interface SMAF HTTP"),
	tmafHTTPRequestErrors(16000, "TMAF HTTP request ended with errors. Details see error lines in the response body"),
	domainNameUserNotAllowed(16001, "The domain name  of the logged in user is not allowed, only the ampus domain is allowed for GMF usage"),
	domainNameUnknown(16002, "The domain name is unknown"),
	emptyCommandOrOperation(16500, "Empty request, transaction,Command or operation"),
	nameNotSetForOeration(16501, "Name is not set for operation or parameter type"),
	invalidSymbolicValueForParameterTypeOrName(16502, "Invalid symbolic value for parameter type or parameter name"),
	invalidSymbolicValueForParameterType(16503, "Invalid symbolic value for parameter type"),
	indexNotSetForParameterTyypeOrName(16504, "Invalid symbolic value for parameter type"),
	attributeNotAllowedForParameterAttributeOrType(16505, "Attribute is not allowed for parameter attribute or parameter type"),
	attributeMustNotEmpty(16506, "Attribute must not be empty"),
	attributeMustNotEmptyForElement(16507, "Parameter attribute must not be empty for element"),
	attributeMustNotContain(16508, "Parameter attribute must not contain \'::\' for element "),
	attributeMustNotStartWith(16509, "Parameter attribute must not start with \'::\'"),
	attributeMustNotContainSequence(16510, "Parameter attribute must not contain a sequence of \'::\'"),
	attributeNotAllowedForInsidParameter(16511, "Parameter attribute is not allowed for inside"),
	nullMustNotSetForValue(16513, "NULL must not be set for parameter type value"),
	valueMustNotEmpty(16514, "Parameter type must not be empty"),
	notValidIdentifier(16515, "String which should be checked if it is valid identifier(name, namespace or modifier)"),
	cannotConsistCapitalLttersAnUnderscoresOnly(
			16516,
			"Attribute Name cannot consist of capital letters and underscores only if the attribute is set to @"),
	undefinedTypeParameter(16517, "Undefined type parameter for parameter name"),
	errorWhileReadingValue(16518, "Error while reading value for parameter type"),
	attributeNotInsideAllowedRange(16519, "Attribute name is not inside allowed range"),
	attributeMayConsistOfExactly(16520, "Attribute Name may consist of exactly"),
	isNotSupported(16521, "Attribute name Or parameter type is not supported"),
	isNotWithinAllowedRange(16522, "Attribute name of parameter type is not within allowed range"),
	isNotValidValue(16523, "Attribute name Or parameter type is not a valid allowed range"),
	unknownPage(16900, "Unknown page"),
	unknownMessagetype(16901, "Unknown messagetype"),
	unknownInternalError(16902, "Unknown internal error while executing a SOAP request"),
	transactionAlreadyTerminated(13101, "transaction already terminated"),
	cannotRollback(13102, "Cannot roll back transaction"),
	invalidValue(13401, "Invalid value for Attribute name Or value"),
	lookupFailed(13402, "Lokkup of component name is Failed"),
	releaseFailed(13403, "Release of Component name is failed"),
	cannotObtainConfigurationData(13404, "Cannot obtain the configuration parameter name"),
	dateTimeFormatError(13405, "Attribute name has invalid DtaTime format value"),
	floatFormatError(13406, "Attribute name has invalid Float format value "),
	intFormatError(13407, "Attribute name has invalid int format value"),
	longFormatError(13408, "Attribute name has invalid long format Value"),
	byteFormatError(13409, "Attribute name has invalid byte format value "),
	shortFormatError(13410, "Attribute name has invalid short format value"),
	doubleFormatError(13411, "Attribute name has invalid double format value"),
	booleanFormatError(13412, "Attribute name has invalid boolean format value"),
	formatErrorType(13413, "Type of attribute name is not supported for this method"),
	notDefinedDataModel(13414, "Entity name or attribute is not defined data model"),
	hasNofunctionRight(13415, "Customer has no function right for  access of Name or Attribute"),
	hasNoAccess(13416, "Customer  has no  access for Level or AttributeName"),
	tooManyKeyAttributesDefined(13417, "Wrong key attributes"),
	missingAttributes(13418, "The key is incomplete Missing Attributes"),
	invalidAttributeModifier(13419, "invalid Attribute modifier "),
	maximumOperations(13420, "Maximum operations per transaction exceeded"),
	resultsetExceeded(13421, "Maximum size of resultset exceeded."),
	primaryKeyAlreadyExists(13422, "primary key already exists"),
	primaryKeyAlreadyExists1(13423, "primary key already exists"),
	entitySizeLimitExceeded(13424, "Entity size limit exceeded the maximum size"),
	checkFlagAllowed(13425, "The operation is sent with {0} Check Flag, which is not allowed"),
	nameInactive(13426, "Name is inactive"),
	parsingError(13427, "Parsing error: generic configuration"),
	ratePrefetchRetrievalNotAllowed(13428, "Rate Prefetch Retrieval is not allowed within a transaction block"),
	ratePrefetchRetrievalNotValid(13429, "Rate Prefetch Retrieval is not valid on nested entities"),
	eventdateMandatory(13430, "Eventdate is mandatory in Rate Prefetch Retrieval operation"),
	keyIncomplete(13431, "The key is incomplete"),
	invalidFormat(13432, "The filter parameter {0} has got an invalid format"),
	invalidOperation(13433, "The filter parameter {0} has got an invalid operation"),
	pagingFunctionalityNotSupported(13434, "Paging functionality - not supported for {0} operation operation name"),
	pagingFunctionalityNotSupportedForNested(13435, "Paging functionality - not supported for Nested entities (entity: {0})"),
	pagingFunctionalityMissingControlAttribute(13436, "Paging functionality - missing control attribute {0}"),
	pagingFunctionalityInvalidControlAttribute(13437, "Paging functionality - invalid control attribute: {0}, value: {1}"),
	controlParameterInvalidOperation(13438, "The control parameter {0} has got an invalid operation"),
	invalidControlAttribute(13439, "Invalid control Attribute (@{0})"),
	invalidGenericAttribute(13440, "Invalid generic Attribute: {0}, value: {1}"),
	genericAttributeError(13441, "Generic Attribute: {0}, value: {1} is {2}"),
	attributeOperationError(13442, "Attribute ({1}) is provided for a {2} operation"),
	dataInconsistencyError(13443, "FUS Attributes not contained because of data inconsistency"),
	requestedFunctionNotSupported(13445, "{0} - The requested function is not supported for {1}"),
	attributeMissing(13446, "The operation requires the following Attribute which is missing now: {0}"),
	nonTimeWindowOperation(13447, "Non-TimeWindow Operation: no exact match for the {0} attribute found for the {1}"),
	attributeProvidedInputError(13448, "The {0} Attribute provided in input is not equal to the calculated one for the {1}"),
	hostingEntityNotAllowed(13449, "The Hosting Entity of an NGE must be a Generic Entity, type {0} for the HOST is not allowed "),
	conflictOperation(13450, "Conflict: {0} operation is not allowed for entities, which do not have {0}ed attributes "),
	oneHostingEntityAllowed(13451, "Only one hosting Entity structure is allowed."),
	nameSpaceConstraint(13452, "The namespace should be {0}"),
	maximumNameSpace(13453, "The maximum number of the namespaces is 1."),
	attributeAlreadyInserted(13454, "The Attribute {0} is already inserted. "),
	inValidOperator(13455, "There is an invalid operator for a hosting entity structure"),
	invalidAttributeModifier1(13456, " invalid Attribute modifier"),
	operationNameInvalid(13457, "The operation name is invalid."),
	complexAttributeError(13458, "List mustn't have complex Attribute."),
	structComplexAttributeError(13459, "Struct mustn't have complex Attribute"),
	valueNull(13460, "value is null."),
	elementValueNull(13461, "Element value is null."),
	parameterNameEmptyError(13462, "A parameter name is empty or null."),
	listParameterNameError(13463, "List mustn't have parameter name. The list parameter is: {0} Name of parameter"),
	formatError(13464, "Format Error: Attribute "),
	hostingEntityAccessError(13465, "Hosting Entity for access of entity "),
	entityBelongingError(13466, "The {0} Entity has belongings (version, bucket, nested)"),
	formatError1(13467, "Format Error: Operation :following fields are multiple"),
	formatError2(13468, "Format Error: Attribute : provided with Index"),
	formatError3(13469, "Format Error: Attribute (type: {1}): provided with value and delete modifier"),
	formatError4(13470, "Format Error: Attribute (type: {1}): provided as null, although it is not nullable"),
	formatError5(13471, "Format Error: Attribute (type: {1}): provided as Simple Attribute"),
	formatError6(13472, "Format Error: Attribute(type: {1}): has Element although it is not allowed"),
	domainNameNotAllowed(13473, "The domain name is <local>, which is not allowed, only the Campus domain is allowed for GMF usage"),
	outputOptimizationWithoutAttributes(13474, "Output customization was defined without attributes"),
	pkAttributeError(13475, "PK fields control parameter was defined together with PK attibutes(s)"),
	outputOperatorError(13476, "Output Attribute was defined with modifier."),
	hostingKeyOutputError(13477, "Hosting key was defined in the output together with no NGE."),
	invalidControlParameterOutput(13478, " Invalid control parameter in output specification (@{2})"),
	notDefinedinGDR(13479, "Attribute is not defined in the GDR."),
	structAttributeDefined(13480, "Struct Attribute with Index was defined in output."),
	indexedAttributeElement(13481, "The output struct Attribute has an indexed element"),
	structAttributeWithModifier(13482, "The output struct attribute has element with modifier"),
	controlParameterNotAllowed(13483, "This control parameter is not allowed with other output Attribute(s) together."),
	outputAttributeNotAllowedTwice(13484, "Output Attribute is not allowed in twice."),
	attributeNotHostingKey(13485, "Attribute  is not a hosting key."),
	outputElementNotAllowedForCustomization(13486, "This output Element type is not allowed for customization."),
	outputAttributeDefinedNotCorrectType(13487, "Output Attribute  was defined with not correct type."),
	outputAttributeNotAllowedWithCurrentOperation(13488, "Output Attribute  is not allowed with the current operation."),
	outputControlAttributeNotAllowed(13489, "Output control Attribute  is not allowed."),
	attributeNotAllowed(13490, "This Attribute  is not allowed for output customization."),
	inputAttributeMissing(13491, "This Attribute  did not find in input attributes"),
	hostingKeyAttributeError(13492, "Output hosting key Attribute is not part of hosting key input attributes"),
	structTypeError(13493, "Struct type is allowed only for hosting key with the current operation."),
	invisibleElementUsed(13494, "Invisible Elements are used: "),
	operationNotAllowedInsideTransaction(13495, "operation is not allowed inside Transaction"),
	touchExecutionFailed(13496, "Touch execution failed: "),
	bucketRolloverFailed(13497, "Bucket rollover invocation failed"),
	eventWritingFailed(13498, "Event writing about the GMAF operation is failed"),
	eventSupportComponentUnavailable(13499, "GMAF Event support component is unavailable"),
	unexpectedOutputEntityType(13500, "The expected Entity type was {0}, but {1} Entity type was found."),
	entityWasNotFound(13501, "With the given selection values : Entity Name was not found"),
	offsetAndMaxcountNotAllowed(13502, "@Offset and @MaxCount are not allowed with EK Attribute in the input"),
	notAllowedWithEkAttribute(13503, "@LasFoundKey and @MaxCount are not allowed with EK Attribute in the input"),
	operationCalledWithoutModifier(13504, "Operation Name is called without modifier"),
	customerLocked(401, "Customer Is Locked"),
	operationFeeNotDefined(501, "Operation Fee Not Defined"),
	/* activeEndDateNotSetToPast(502,"Active End Date cannot be set to past"), */
	/* invalidParameterValue1(503,"InvalidParameterValue"), */
	/* serviceNotAllowed(500,"Service Not Allowed"), */
	offerChangeNotAllowedForTCLSubscriber(4056, "Offer Change is not allowed for the TCL subscriber due to Outstanding Amount "),
	invalidParameterValueError(103, "Invalid parameter value"),
	missingMandatoryParameterError(102, "Missing mandatory parameter"),
	customerIsLocked(801, "Customer locked"),
	/* invalidCustomerLifecycle(502,"Invalid customer lifecycle state"), */
	eventNotFound(503, "Event not found"),
	technicalError(505, "Technical error"),
	missingParameterError(420, "Missing mandatory Parameter"),
	invalidParameterValueForSelectionCode(421, "Invalid parameter value for selectionCode"),
	invalidLifecycleError1(602, "Invalid lifecycle"),
	slcActivationNotSuccessful(507, "Slc activation not successful"),
	technicalError1(508, "Technical error"),
	nonExistentAccount(201, "Non existent account"),
	duplicateDetection(403, "Recharge ignored due to duplicate detection, It is duplicate to Recharge ExecutedAt <dateandtime >"),
	daysExtensionNotSpecified(900, "Days of extension not specified"),
	invalidEventName(999, "Invalid Event Name"),
	usecaseInvalid(4001, "Usecase invalid."),
	operationInvalidError(4002, "Operation invalid."),
	subscribeNotAllowed(4007, "subscribe not allowed"),
	undefinedParameterError(4010, "undefined parameter"),
	invalidParameterType(4011, "invalid parameter type"),
	unspecificError(4040, "unspecific error"),
	notValidPreActiveEndDate(4020, "Not a Valid Pre Active End Date"),
	notPreActive(4020, "User is not preactive"),
	notInGrace(4020, "User is not Grace"),
	SLAExhaust(99999, "SLA Exhaust");
	private final int		code;
	private final String	message;

	private ErrorCode(final int code, final String message) {
		this.code = code;
		this.message = message;
	}

	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

}
