package org.csapi.wsdl.parlayx.payment.reserve_amount_charging.v2_1._interface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-03-19T15:42:32.226+07:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebService(targetNamespace = "http://www.csapi.org/wsdl/parlayx/payment/reserve_amount_charging/v2_1/interface", name = "ReserveAmountCharging")
@XmlSeeAlso({org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class, org.csapi.schema.parlayx.payment.v2_1.ObjectFactory.class, org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ObjectFactory.class})
public interface ReserveAmountCharging {

    @RequestWrapper(localName = "releaseReservation", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReleaseReservation")
    @WebMethod
    @ResponseWrapper(localName = "releaseReservationResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReleaseReservationResponse")
    public void releaseReservation(
        @WebParam(name = "reservationIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        java.lang.String reservationIdentifier
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;

    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
    @RequestWrapper(localName = "reserveAmount", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReserveAmount")
    @WebMethod
    @ResponseWrapper(localName = "reserveAmountResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReserveAmountResponse")
    public java.lang.String reserveAmount(
        @WebParam(name = "endUserIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        java.lang.String endUserIdentifier,
        @WebParam(name = "charge", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        org.csapi.schema.parlayx.common.v2_1.ChargingInformation charge
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;

    @RequestWrapper(localName = "chargeReservation", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ChargeReservation")
    @WebMethod
    @ResponseWrapper(localName = "chargeReservationResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ChargeReservationResponse")
    public void chargeReservation(
        @WebParam(name = "reservationIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        java.lang.String reservationIdentifier,
        @WebParam(name = "charge", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        org.csapi.schema.parlayx.common.v2_1.ChargingInformation charge,
        @WebParam(name = "referenceCode", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        java.lang.String referenceCode
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;

    @RequestWrapper(localName = "reserveAdditionalAmount", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReserveAdditionalAmount")
    @WebMethod
    @ResponseWrapper(localName = "reserveAdditionalAmountResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local", className = "org.csapi.schema.parlayx.payment.reserve_amount_charging.v2_1.local.ReserveAdditionalAmountResponse")
    public void reserveAdditionalAmount(
        @WebParam(name = "reservationIdentifier", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        java.lang.String reservationIdentifier,
        @WebParam(name = "charge", targetNamespace = "http://www.csapi.org/schema/parlayx/payment/reserve_amount_charging/v2_1/local")
        org.csapi.schema.parlayx.common.v2_1.ChargingInformation charge
    ) throws org.csapi.wsdl.parlayx.common.v2_0.faults.PolicyException, org.csapi.wsdl.parlayx.common.v2_0.faults.ServiceException;
}
