
package com.nsn.ossbss.charge_once.wsdl.entity.tis.wsdl._1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-07-17T22:30:35.393+08:00
 * Generated source version: 2.6.0.redhat-60024
 */

@WebFault(name = "FaultMessage", targetNamespace = "http://nsn.com/ossbss/charge.once/wsdl/entity/Tis/xsd/1")
public class TisException extends Exception {
    
	private static final long serialVersionUID = 1L;
	
	private com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.FaultMessage faultMessage;

    public TisException() {
        super();
    }
    
    public TisException(String message) {
        super(message);
    }
    
    public TisException(String message, Throwable cause) {
        super(message, cause);
    }

    public TisException(String message, com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.FaultMessage faultMessage) {
        super(message);
        this.faultMessage = faultMessage;
    }

    public TisException(String message, com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.FaultMessage faultMessage, Throwable cause) {
        super(message, cause);
        this.faultMessage = faultMessage;
    }

    public com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.FaultMessage getFaultInfo() {
        return this.faultMessage;
    }
}
