package com.nsn.ossbss.charge_once.wsdl.entity.tis.wsdl._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-07-17T22:30:35.421+08:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebService(targetNamespace = "http://nsn.com/ossbss/charge.once/wsdl/entity/Tis/wsdl/1",
serviceName="TisService",
name="Tis",
portName="TisSoapPort")
@XmlSeeAlso({com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TisInterface {

    @WebResult(name = "CommandResponseData", targetNamespace = "http://nsn.com/ossbss/charge.once/wsdl/entity/Tis/xsd/1", partName = "response")
    @WebMethod(operationName = "ExecuteCommand")
    public com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.CommandResponseData executeCommand(
        @WebParam(partName = "request", name = "CommandRequestData", targetNamespace = "http://nsn.com/ossbss/charge.once/wsdl/entity/Tis/xsd/1")
        com.nsn.ossbss.charge_once.wsdl.entity.tis.xsd._1.CommandRequestData request
    ) throws TisException;
}
